### ISSUE TITLE
mock slow requests

### ISSUE THREAD

**Issue by Saqibm128** [Tabueeee/puppeteer-request-spy#13]
is there a way to pass a callback function to the mockFakeResponse function to do arbitrary logic, such as waiting for a certain amount of time for certain responses?

**Comment by Tabueeee** [comment]
Hi @Saqibm128 ,
Sorry for not answering sooner. I assume you are asking about the IResponseFaker to allow for an asynchronous getResponseFake function. Sadly in this version the RequestInterceptor expects the callback to return the RespondOptions directly.

I have already adressed this issue in the next version (1.4). Altough I prepared the code some time ago, I have yet to finish testing full backwards compatibility and writing documentation for alle the new features :)

So you now have 3 options:
  1. apply a Hotfix yourself
  2. Wait for me to push the next branch to Github (next weekend) and build the module
  3. Wait for me to publish the next branch to npm (maybe next month?)

If you want to apply a Hotfix yourself it will includes two steps:
- replace node_modules/puppeteer-request-spy/build/RequestInterceptor.js
- add node_modules/puppeteer-request-spy/build/common/resolveOptionalPromise.js
[RequestInterceptor.js.txt](https://github.com/Tabueeee/puppeteer-request-spy/files/4908446/RequestInterceptor.js.txt)
[resolveOptionalPromise.js.txt](https://github.com/Tabueeee/puppeteer-request-spy/files/4908447/resolveOptionalPromise.js.txt)

Github doesn't allow me to attach .js files so rename them first ;)

If you want to build the module:
- clone the repository / branch 1.4
- in cloned root: npm run release-dry
- in your project: npm i path-to-cloned-root/puppeteer-request-spy-1.4.0.tgz
