### ISSUE TITLE
Feature Suggestion: Mocking based on method

### ISSUE THREAD

**Issue by dbartholomae** [Tabueeee/puppeteer-request-spy#8]
Hi there,

we are using puppeteer-request-spy for testing our frontend. In one test there is both a GET to `/messages` as well as a POST later on. These need to return different answers. Is there a preferred solution already how to solve this with this library? Otherwise I would suggest adding the possibility to match not only by path, but also by method. This should be possible to do without a breaking change.
We would be willing to provide a PR, though a short introduction into your test set up might be needed.

Best,
Daniel

**Comment by Tabueeee** [comment]
Hi Daniel,

First of all thank you for the valuable input. I did not think about this use case yet so there is no preferred way as of now.

But I really like your Feature idea and I will definitely find a way to integrate it. I took a quick look into the project and it should be no problem to implement.

My preferred solution would be to allow any Faker / Spy to have its own optional matcher function. This function would allow you to check the request for any info and return true if the criteria matches. Puppeteer’s request object already has a convenient function to get the request method or headers as specified here: [puppeteer API](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-request)

Your test code after the new release may look something like this:
````js
function matchRequestMethod(method) {
	return (request) => request.method() === method;
}

let getMessageFaker = new ResponseFaker('/message', fakeGetResponse);
getMessageFaker.setMatcher(matchRequestMethod('GET'));

let postMessageFaker = new ResponseFaker('/message', fakePostResponse);
getMessageFaker.setMatcher(matchRequestMethod('POST'));
...
````
I may have some spare time this weekend, if so this feature could be available by next week. Further input is always welcome!

Regards,
Tobias

**Comment by dbartholomae** [comment]
Hi Tobias,

sounds great! I've looked through the code and would suggest the following changes:
Use a `ResponseFaker` interface instead of directly relying on the class. This way others can implement their own Fakers. The next easy step would be to call `getResponseFake(request)` with the actual request as a parameter. This will make implementation very flexible and would already solve most of the problem as we could have one `ResponseFaker` that reacts to the request's method.

A next step could be to use an `isMatch` method on the `ResponseFaker` and `ResponseSpy` instead of `getPatterns`. To not be a breaking change this method would need to get both the `request` as well as the `matcher` when called, so the existing implementations can still work the same way.

Best,
Daniel

**Comment by Tabueeee** [comment]
Hi Daniel,

Talk about missing the obvious! Of course interfaces... I may have been thinking too much in terms of a package consumer rather than a package provider. I definitely have some rethinking to do about how to open up my code in general.

I thought about your changes and I do prefer them. It's definitely the most flexible way to provide you with the desired functionality. Thank you for taking time for such a detailed look into the project.

If you have any future feature Request please share! One of my biggest Problems is that we currently do not use the Faking Feature ourselves so I have no real feedback. 
That's why I am so happy about your Issue :)

Regards,
Tobi

**Comment by dbartholomae** [comment]
Hi Tobi,

sounds good! If you are not already working on it, I would also be happy to provide a PR.

Best,
Daniel
